### ISSUE TITLE
TypeError thrown when Google account has no alerts

### ISSUE THREAD

**Issue by shaneiseminger** [adasq/google-alerts-api#23]
/app/node_modules/google-alerts-api/src/alerts.js:232
        return state[0][0];
                       ^

TypeError: Cannot read property '0' of null
    at Object.getAlertsByState (/app/node_modules/google-alerts-api/src/alerts.js:232:24)
    at Object.getAlerts (/app/node_modules/google-alerts-api/src/api.js:77:31)
    at alerts.sync (/app/api/controller.js:33:26)
    at Request.getCb [as _callback] (/app/node_modules/google-alerts-api/src/api.js:69:13)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)

**Comment by shaneiseminger** [comment]
Thanks!
