### ISSUE TITLE
Running in Jest - ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

### ISSUE THREAD

**Issue by Krzysztof-Dziardziel** [adasq/google-alerts-api#36]
Hello.

I have this kind of code in my test file:
```
test('Can fetch alert list', () => {
    alerts.configure({
        cookies: process.env.GOOGLE_ALERTS_COOKIE,
    });
    alerts.sync(() => {

        const alertList = alerts.getAlerts();
        alertList.forEach((alert:any) => console.log(alert))

        expect(alertList).toBeTruthy();

    })
})
```

It throws an error:
```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. 
at Function.Object.<anonymous>.exports.load (node_modules/cheerio/lib/static.js:18:17) 
at Object.getStateByBody (node_modules/google-alerts-api/src/alerts.js:70:31) 
at Request.getCb [as _callback] (node_modules/google-alerts-api/src/api.js:66:24) 
at Request.self.callback (node_modules/google-alerts-api/node_modules/request/request.js:185:22)
```

Do You know how should I proceed to fix it?

**Comment by adasq** [comment]
It's out of the scope of the package.
Please, follow the guidelines here:
https://github.com/facebook/jest/issues/6434
