### ISSUE TITLE
Cannot create mail alert

### ISSUE THREAD

**Issue by ilya-nurullin** [adasq/google-alerts-api#5]
```js
const alerts = require('google-alerts-api');
alerts.configure({
    mail: 'your_mail@gmail.com',
    password: '**********'
});

const { HOW_OFTEN, DELIVER_TO, HOW_MANY } = alerts;

alerts.sync(() => {
    const alertToCreate = {
        howOften: HOW_OFTEN.AT_MOST_ONCE_A_DAY,
        sources: [],
        lang: 'en',
        name: 'NodeJS AND "Chrome V8"',
        region: 'PL',
        howMany: HOW_MANY.BEST,
        deliverTo: DELIVER_TO.MAIL,
        deliverToData: ''
    };

    alerts.create(alertToCreate, (err, alert) => {
        console.log(err);
        console.log(alert);
    });
});
```
Console output:
```
TypeError: Cannot read property '0' of undefined
    at Request.reqHandler.create [as _callback] (D:\OSPanel\domains\dev.dev\node_modules\google-alerts-api\src\api.js:117:38)
    at Request.self.callback (D:\OSPanel\domains\dev.dev\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (D:\OSPanel\domains\dev.dev\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (D:\OSPanel\domains\dev.dev\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
undefined
```

**Comment by adasq** [comment]
You should provide your mail in `deliverToData` field, in order to create alert. It musn't be empty

**Comment by adasq** [comment]
Closing, if still does not work, feel free to reopen.
