### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'cookies.data'

### ISSUE THREAD

**Issue by salshyn** [adasq/google-alerts-api#8]
```
[nodemon] restarting due to changes...
[nodemon] starting `node index.js`
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open 'cookies.data'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at Object.<anonymous> (/Users/.../index.js:26:15)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
[nodemon] app crashed - waiting for file changes before starting...
```

Apparently comes from here:

> alerts.generateCookies('sample-email@gmail.com', 'sample-pass', (err, cookies) => {
>   if(err) return console.log(err);
>   fs.writeFileSync('cookies.data', cookies);
> });

**Comment by salshyn** [comment]
Please note, that some accounts work, but some not. What is wrong with accounts that are not working? 2-way is turned off for them just like for others.

**Comment by adasq** [comment]
As far as I remember, I had to enable `access to less secure apps` on google account. More here: https://support.google.com/cloudidentity/answer/6260879?hl=en.

Check it out and let me know, whether it has helped you.
